-- 코드를 입력하세요
SELECT ANIMAL_TYPE, COUNT(ANIMAL_ID) 'count'
FROM ANIMAL_INS
# WHERE ANIMAL_TYPE ='Cat' OR ANIMAL_TYPE = 'Dog'
GROUP BY ANIMAL_TYPE HAVING ANIMAL_TYPE IN ('Cat', 'Dog')
# ORDER BY ANIMAL_TYPE
ORDER BY FIELD (ANIMAL_TYPE, 'Cat','Dog')