-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, 
CASE WHEN (UGB.STATUS = 'SALE') THEN '판매중'
WHEN (UGB.STATUS = 'RESERVED') THEN '예약중'
ELSE '거래완료' END 'STATUS'
FROM USED_GOODS_BOARD UGB
WHERE CREATED_DATE = '2022-10-05'
ORDER BY BOARD_ID DESC