-- 코드를 입력하세요
SELECT *
FROM (SELECT  A.NAME, A.DATETIME
      FROM ANIMAL_INS A
      LEFT JOIN ANIMAL_OUTS B 
      ON B.ANIMAL_ID = A.ANIMAL_ID
      WHERE B.ANIMAL_ID IS NULL
      ORDER BY A.DATETIME)
WHERE ROWNUM <=3;