-- 코드를 입력하세요
SELECT # (PRICE DIV 10000) * 10000 PRICE_GROUP,
CASE WHEN LENGTH(PRICE) > 4 THEN LEFT(PRICE,1)*10000
WHEN LENGTH(PRICE) <= 4 THEN 0 END PRICE_GROUP, 
COUNT(*) PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP