-- 코드를 입력하세요
SELECT B.CATEGORY, sum(BS.SALES) TOTAL_SALES
FROM BOOK B
JOIN BOOK_SALES BS
ON BS.BOOK_ID = B.BOOK_ID
WHERE MONTH(BS.SALES_DATE) = 01 AND YEAR(BS.SALES_DATE) = 2022
GROUP BY B.CATEGORY
ORDER BY CATEGORY