-- 코드를 입력하세요
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE,'%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD UGB
JOIN USED_GOODS_REPLY UGR
ON UGR.BOARD_ID = UGB.BOARD_ID
WHERE MONTH(UGB.CREATED_DATE) = 10
ORDER BY UGR.CREATED_DATE, UGB.TITLE