-- 코드를 입력하세요
SELECT DISTINCT(OA.USER_ID), OA.PRODUCT_ID
FROM ONLINE_SALE OA
JOIN ONLINE_SALE OB
ON OA.PRODUCT_ID = OB.PRODUCT_ID AND OA.USER_ID = OB.USER_ID
WHERE OA.SALES_DATE != OB.SALES_DATE
ORDER BY USER_ID, PRODUCT_ID DESC;