-- 코드를 입력하세요
SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT P
LEFT JOIN FOOD_ORDER O
ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE MONTH(O.PRODUCE_DATE) = '05' AND YEAR(O.PRODUCE_DATE) ='2022'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC