-- 코드를 입력하세요
SELECT DISTINCT(CRC.CAR_ID) 
FROM  CAR_RENTAL_COMPANY_CAR  CRC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH
ON CRH.CAR_ID = CRC.CAR_ID
WHERE MONTH(CRH.START_DATE) = 10 
AND CRC.CAR_TYPE = '세단'
ORDER BY CRH.CAR_ID DESC