-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
WHERE A.DATETIME > (SELECT B.DATETIME 
                   FROM ANIMAL_OUTS B
                   WHERE A.ANIMAL_ID = B.ANIMAL_ID)
ORDER BY A.DATETIME
-- FROM (SELECT A.DATETIME, A.ANIMAL_ID, A.NAME, B.DATETIME
--      FROM ANIMAL_INS A 
--      LEFT JOIN ANIMAL_OUTS B 
--      ON B.DATETIME < A.DATETIME
--      ORDER BY A.DATETIME)
     